version: '3.1'

services:

  db:
    image: postgres:13.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: carpocketbook
    ports:
      - 5577:5432

  client:
    image: local/app-client:latest
    environment:
      PROTOCOL: http
      SERVER_URL: monobackend:8080
      PORT: 8001
    ports:
      - 8001:8001
    depends_on:
      - monobackend

  monobackend:
    image: local/monobackend:latest
    environment:
      PG_USERNAME: postgres
      PG_PASSWORD: 1234
      PG_URL: db:5432/carpocketbook
    depends_on:
      - db