version: '3.1'

services:

  db:
    image: postgres:13.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: carpocketbook
    ports:
      - 5577:5432

  keycloak:
    image: jboss/keycloak:12.0.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: carpocketbook
      DB_USER: postgres
      DB_PASSWORD: 1234
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - db

#  nginx:
#    image: nginx:1.17.5
#    volumes:
#      - ./templates/nginx.conf:/data/conf/nginx.conf
#      - ./app-client/dist/app-client:/usr/share/nginx/html
#    ports:
#      - 4300:80
#    environment:
#      - PROTOCOL=http
#      - SERVER_URL=127.0.0.1:8086
#      - NGINX_PORT=80
#  gateway:
#    image: local/gateway
#    ports:
#      - 8086:8086
#    depends_on:
#      - keycloak

#  monobackend:
#    image: local/monobackend:latest
#    restart: unless-stopped
#    environment:
#      PG_USERNAME: postgres
#      PG_PASSWORD: 1234
#      PG_URL: db:5432/carpocketbook
#      ISSUER_URI: http:127.0.0.1:8888/auth/realms/master
#    ports:
#      - 8082:8082
#    depends_on:
#      - keycloak
#
#  client:
#    image: local/app-client:latest
#    environment:
#      PROTOCOL: http
#      SERVER_URL: monobackend:8080
#      PORT: 8001
#    ports:
#      - 8001:8001
#    depends_on:
#      - monobackend