version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: carpocketbook
    ports:
      - 5577:5432

  app-server:
    container_name: server
    image: docker.pkg.github.com/mrak2017/car-maintenance-pocketbook/monobackend:latest
    ports:
      - 8002:8080
    depends_on:
      - db
    links:
      - db
