name: Client on Heroku

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Puch to Heroku
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: push to heroku
        env :
          HEROKU_REGISTRY_URL: registry.heroku.com
          HEROKU_TOKEN : ${{ secrets.HEROKU_API_KEY }}
          SERVER_URL: ${{ secrets.GOOGLE_CLOUD_SERVER_URL }}
          PROTOCOL: https
        run : |
          docker login --username=_ --password $HEROKU_TOKEN $HEROKU_REGISTRY_URL
          export HEROKU_API_KEY=$HEROKU_TOKEN
          heroku container:login
          heroku config:set SERVER_URL=$SERVER_URL --app car-pocketbook
          heroku config:set PROTOCOL=$PROTOCOL --app car-pocketbook
          heroku container:push web --app car-pocketbook
          heroku container:release web --app car-pocketbook
          heroku ps:scale web=1 --app car-pocketbook